### ISSUE TITLE
Misleading statement about let syntax in do-blocks

### ISSUE THREAD

**Issue by googleson78** [triffon/fp-slides#5]
You have to squint very hard to make the statement "`let x = y` in a do-block is syntactic sugar for `x <- pure y`" true.

Reasons to not claim this:
* They are not required to be operationally the same, only denotationally.
* Unlawful `Monad` instances - if `pure` and `(>>=)` do not obey the `Monad` laws, then this is not true
* The equivalence breaks if you do any pattern matching with `x` - the `let` binding will throw an "incomplete pattern match" exception, whereas the bind version will use `fail` for the `Monad(Fail)`
* `let` in a do-block is actually syntactic sugar for `let...in...`

**Comment by triffon** [comment]
Thank you, corrected the slide in b3f8e2903b6519b5326ea010ce8e6fcf71f85583 so that it no longer incorrectly claims that `let` in a `do` block is syntactic sugar for `x <- return y`, but simply states that these are two alternative mechanisms, which can be used to achieve a local definition in a `do` block.
